# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: howCatCanCode
email: sawantpshubham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about all the stuff I’m doing related to Computer Science and Information Technology.
  Following this blog would help you grow. 
  It’ll add up many new resources for learning help you to understand Computer Science fundamentals.
  We discuss Ideas here. Let’s CODE.
baseurl: "/howCatCanCode" # the subpath of your site, e.g. /blog
url: "http:moghya.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: moghya
github_username:  moghya

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
